BaseURL = "https://www.mywebsite.com/"
languageCode = "en-us"
title = "My Hugo Site"
theme = "mytheme"
relativeURLS = true
sectionPagesMenu = "main"





[module]
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"


[menu]
    [[menu.main]]
        name = "Research"
        url = "/research/"
        weight = 10
    [[menu.main]]
        name = "Publications"
        url = "/publications/"
        weight = 20
    [[menu.main]]
        name = "Members"
        url = "/members/"
        weight = 30
    [[menu.main]]
        name = "Education"
        url = "/education/"
        weight = 40
    [[menu.main]]
        name = "News"
        url = "/news/"
        weight = 50